package com.kxsv.schooldiary.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7847A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF1DAFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2D004F)
val md_theme_light_secondary = Color(0xFF8E437E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD7F0)
val md_theme_light_onSecondaryContainer = Color(0xFF3A0033)
val md_theme_light_tertiary = Color(0xFF006B5D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF77F8DF)
val md_theme_light_onTertiaryContainer = Color(0xFF00201B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_outline = Color(0xFF7C757E)
val md_theme_light_inverseOnSurface = Color(0xFFF6EFF3)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFDFB7FF)
val md_theme_light_surfaceTint = Color(0xFF7847A4)
val md_theme_light_outlineVariant = Color(0xFFCDC4CE)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFEF7FC)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE9DFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4B454D)

val md_theme_dark_primary = Color(0xFFDFB7FF)
val md_theme_dark_onPrimary = Color(0xFF471272)
val md_theme_dark_primaryContainer = Color(0xFF5F2E8A)
val md_theme_dark_onPrimaryContainer = Color(0xFFF1DAFF)
val md_theme_dark_secondary = Color(0xFFFFACE8)
val md_theme_dark_onSecondary = Color(0xFF57114D)
val md_theme_dark_secondaryContainer = Color(0xFF732A65)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD7F0)
val md_theme_dark_tertiary = Color(0xFF57DBC4)
val md_theme_dark_onTertiary = Color(0xFF00382F)
val md_theme_dark_tertiaryContainer = Color(0xFF005045)
val md_theme_dark_onTertiaryContainer = Color(0xFF77F8DF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE7E1E5)
val md_theme_dark_outline = Color(0xFF968E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val md_theme_dark_inversePrimary = Color(0xFF7847A4)
val md_theme_dark_surfaceTint = Color(0xFFDFB7FF)
val md_theme_dark_outlineVariant = Color(0xFF4B454D)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF151316)
val md_theme_dark_onSurface = Color(0xFFCBC5C9)
val md_theme_dark_surfaceVariant = Color(0xFF4B454D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC4CE)


val seed = Color(0xFF9361BF)
